apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: edc-datadashboard
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/YOUR_ORG/YOUR_GITOPS_REPO.git
    targetRevision: main
    path: edc-datadashboard/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: edc-datadashboard
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

