apiVersion: v1
kind: Secret
metadata:
  name: edc-datadashboard-secret
  namespace: edc-datadashboard
type: Opaque
stringData:
  # Optional. Keep this only if you later front the dashboard with basic auth
  placeholder: "placeholder"
